#!/usr/bin/env bash
# shellcheck disable=SC1090

dir="${XDG_CONFIG_HOME:-${HOME}/.config}/bash/aliases"
if [ -d "${dir}" ]; then
	#source "${dir}/nslookup.exe"
	#source "${dir}/exa.sh"
	source "${dir}/grep.sh"
	source "${dir}/ls.sh"
	source "${dir}/navigation.sh"
	#source "${dir}/which.sh"
	#source "${dir}/zoxide.sh"
	source "${dir}/interaction.sh"
	source "${dir}/permissions.sh"
	source "${dir}/file-management.sh"
	source "${dir}/explorer.sh"
	source "${dir}/mkdir.sh"
	#source "${dir}/doas.sh"
	source "${dir}/rc.sh"
	source "${dir}/shellcheck.sh"
	source "${dir}/bat.sh"
	source "${dir}/caffeine.sh"
	source "${dir}/urlscanio.sh"
	source "${dir}/clip.sh"
	source "${dir}/winget.sh"
	source "${dir}/vim.sh"
	source "${dir}/neovim.sh"
	source "${dir}/code-insiders.sh"
	source "${dir}/latex.sh"
	source "${dir}/curl.sh"
	source "${dir}/netcat.sh"
	source "${dir}/ps.sh"
	source "${dir}/youtube-dl.sh"
	#source "${dir}/session.sh"
	source "${dir}/git.sh"
	#source "${dir}/subversion.sh"
	source "${dir}/gitclone.sh"
	source "${dir}/sshman.sh"
	source "${dir}/mkcd.sh"
	source "${dir}/fat-finger.sh"
fi
unset dir
