#!/usr/bin/env bash
#
# Author:	Alex Paarfus <stewie410@gmail.com>
#
# Displays the current state & capacity of all batteries (multi-line)

# Ensure vars are always unset
trap "unset d c s" EXIT

# Iterate over device files
find "/sys/class/power_supply" -mindepth 1 -maxdepth 1 -wholename "*BAT*" -exec readlink --canonicalize {} \; | while read -r d; do
    # Get Capacity & Status
    c="$(cat "${d}/capacity")"
    s="$(sed 's/discharging//I;s/not charging/X/I;s/charging//I;s/unknown/?/I;s/full//I' "${d}/status")"

    # Display Status
	printf '%s\n' "${s} ${c}" | awk '$2 < 15 { $1 = " " $1} END { print $1,$2 "%"}'
done
