#!/bin/bash
#
# Author:	Alex Paarfus <stewie410@gmail.com>
# Date:		2020-04-20
#
# Displays the current state of the battery for i3Blocks

# Get Status
cat "/sys/class/power_supply/"{status,capacity} | \
	xargs | \
	sed 's/,//g;s/discharging//I;s/charging//I;s/not charging/X/I;s/unknown/?/I;s/ 0*/ /g;s/ :/ /g' | \
	awk '$2 < 25 { $1 = " " $1} END { print $1,$2% "%"}'
