#!/usr/bin/env bash
#
# network
# Author:	Alex Paarfus <stewie410@gmail.com>
#
# Retrieve network & radio device status

# Declare variabels
declare string
trap "unset string" EXIT

# Handle Mouse Events
case "${BLOCK_BUTTON}" in
	1 ) 	"${TERMINAL}" -e nmtui & disown; exit;;
esac

# Get Status
for i in $(ip route |& awk '/^[0-9]/ {print $3}'); do
    [[ "${i,,}" =~ ^w ]] && { string+=" "; continue; }
    [[ "${i,,}" =~ ^e ]] && { string+=" "; continue; }
    [[ "${i,,}" =~ ^t ]] && { string+=" "; continue; }
done
[ -s "/usr/lib/systemd/system/bluetooth.service" ] && { systemctl --quiet is-active bluetooth && string+=" "; }

# Print Status
printf '%s\n' "${string:-1}"
