#!/bin/bash
#
# network
# Author:	Alex Paarfus <stewie410@gmail.com>
# Date:		2020-04-10
#
# Check for a network connection on both eth and wlp interfaces

# Clear Memory
trap "unset string" EXIT

# Handle Mouse Events
case "${BLOCK_BUTTON}" in
	1 ) 	"${TERMINAL}" -e nmtui & disown; exit;;
esac

# Get Status
declare string
ip route |& sed --quiet '/^[0-9]/p' | grep --quiet --ignore-case "dev w" && string+=" "
ip route |& sed --quiet '/^[0-9]/p' | grep --quiet --ignore-case "dev e" && string+=" "
[ -s "/usr/lib/systemd/system/bluetooth.service" ] && systemctl --quiet is-active bluetooth && string+=" "

# Print Status
[ -n "${string}" ] && printf '%s\n' "${string:-1}"
