#!/bin/bash
#
# updates
# Author:	Alex Paarfus
# Date:		2020-04-10
#
# Get the total number of available packages since last sync
# Requires:
# 	-yay
# 	-checkupdates

# Handle Mouse Events
case "${BLOCK_BUTTON}" in
	1 ) 	pamac-manager & disown; exit;;
esac

# Return if no network connection
ping -c 1 "8.8.8.8" |& grep --quiet --ignore-case "unreachable" && exit 1

# Return if required commands not present
command -v checkupdates >/dev/null || exit 1
command -v yay >/dev/null || exit 1

# Print Available Updates
{ checkupdates | cut --delimiter=" " --fields=1; yay --query --upgrades --foreign --aur --quiet; } | \
	sort | \
	uniq | \
	wc --lines | \
	awk '$1 > 0 { print " " $1 }'
