#!/usr/bin/env bash
#
# volume
# Author:	Alex Paarfus <stewie410@gmail.com>
#
# Get volume stat && control volume

# Return if required commands not found
command -v pamixer >/dev/null || exit 1

# Handle Mouse Events
case "${BLOCK_BUTTON}" in
	1 ) 	pamixer --toggle-mute;;
	3 ) 	"${TERMINAL}" -e pulsemixer 2>/dev/null & disown; exit;;
esac

# Get Status
pamxixer --get-volume-human | sed 's/muted//;s/^/ /'
