#!/usr/bin/env bash
#
# weather
# Author:	Alex Paarfus
#
# Get the weather right now

# Return if offline
ping -c "8.8.8.8" |& grep --quiet --ignore-case "unreachable" && exit 1

# Print Weather
curl --silent --fail "wttr.in/?u&format=%C+%t" | sed 's/+//'
