# Shell variables
# Generated by 'wal'
wallpaper='/home/alex/.config/wpg/wallpapers/mSd9gbH.png'

# Special
background='#121a21'
foreground='#f8ffff'
cursor='#f8ffff'

# Colors
color0='#121a21'
color1='#A36257'
color2='#5B5F65'
color3='#B79962'
color4='#4C689A'
color5='#88718F'
color6='#6CADC6'
color7='#cad1d5'
color8='#233341'
color9='#e47360'
color10='#69798f'
color11='#ffcc6d'
color12='#5382d7'
color13='#b982ca'
color14='#78e9ff'
color15='#f8ffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
