--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alex/.config/wpg/wallpapers/mSd9gbH.png"

-- Special
background="#121a21"
foreground="#f8ffff"
cursor="#f8ffff"

-- Colors
color0="#121a21"
color1="#A36257"
color2="#5B5F65"
color3="#B79962"
color4="#4C689A"
color5="#88718F"
color6="#6CADC6"
color7="#cad1d5"
color8="#233341"
color9="#e47360"
color10="#69798f"
color11="#ffcc6d"
color12="#5382d7"
color13="#b982ca"
color14="#78e9ff"
color15="#f8ffff"
