#!/usr/bin/env bash

alias l='ls'
alias ls='ls --group-directories-first --color=auto --classify'
alias ll='ls -l'
alias la='ls --almost-all'
alias lla='la -l'
alias llh='ll --human-readable'
alias llah='lla --human-readable'

alias lz='ls --context'
alias lza='la --context'
alias lzh='lh --context'
alias lzah='lza --human-readable'

alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias ..='cd ..'
alias ...='cd ../..'

alias mv='mv --interactive'
alias cp='cp --interactive'
alias rm='rm --interactive'

alias grep='grep --color=auto'

alias bat='batcat'

alias wttr='curl --silent --fail wttr.in'
alias pubip='curl --silent --fail ipinfo.io/ip'
alias ipinfo='curl --silent --fail ipinfo.io/json'

alias git='git --no-pager'
alias gdf='git --git-dir="${HOME}/dotfiles" --work-tree="${HOME}"'

alias gcl='${HOME}/scripts/tools/gitclone.sh'

alias xelatexmk='latexmk -xelatex'

alias ipscan='nmap -sn'
alias hnscan='nmap -sU -p137 --script nbstat.nse'

alias shellcheck='shellcheck --color=always'

alias us='urlscanio'
alias usi='us --investigate'
alias uss='us --submit'
alias usg='us --retrieve'

alias vv='vim -u NONE'
alias vn='nvim -u NONE'

alias ytdl='yt-dlp'
alias yta='ytdl --extract-audio'
alias ytv='ytdl'

alias xml='xmlstarlet'

alias sshu='ssh'
alias ssha='ssh -o "User=root"'
alias sshw='ssh -F "${WINHOME/d/c}/.ssh/work/config"'
alias sshwu='sshw'
alias sshwa='sshw -O "User=root"'

alias explorer='explorer.exe'
alias clip='clip.exe'
alias nslookup='/mnt/c/Windows/System32/nslookup.exe'

alias svn='/mnt/c/Program\ Files/TortoiseSVN/bin/svn.exe'

alias user_installed='apt-mark showmanual'
