#!/usr/bin/env bash
# shellcheck source=/dev/null disable=SC2155

# Skip customizations if not running interactively
[[ "${-}" != *i* ]] && return

# Shell options
set -o vi
stty -ixon
shopt -s histappend cdspell checkwinsize checkjobs cmdhist globstar mailwarn no_empty_cmd_completion

# Readline bindings
bind Space:magic-space
bind 'set completion-ignore-case on'
bind 'set completion-map-case on'
bind 'set show-all-if-ambiguous on'
bind 'set mark-symlinked-directories on'
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

# Manpage Pager
command -v batcat &>/dev/null && export MANPAGER="sh -c 'col -bx | batcat --language man --plain'"

# Make LESS more friendly for non-text input files
[[ -x "/usr/bin/lesspipe" ]] && eval "$(SHELL="/bin/sh" lesspipe)"

# PATH
PATH+=":${HOME}/.cargo/bin"
PATH+=":${HOME}/.local/bin"
export PATH

# XDG
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${XDG_DATA_HOME%/*}/state"

# SSH
export SSH_HOME="${HOME}/.ssh/${HOSTNAME}"
export SSH_AUTH_SOCK="${SSH_HOME%/*}/agent.sock"

# History
export HISTSIZE=""
export HISTFILESIZE=""
export HISTCONTROL="ignoreboth,erasedups"
export HISTIGNORE=$'[\t]*:&:[fb]g:exit'

# Environment
export EDITOR="$(command -v nvim)"
export FILE_MANAGER="$(command -v explorer.exe)"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export TERM="${TERM:-xterm-256color}"
export COLORTERM="truecolor"

# LESS colors
export LESS="--RAW-CONTROL-CHARS --ignore-case"
export LESS_TERMCAP_mb="$(tput blink)"
export LESS_TERMCAP_md="$(tput bold)"
export LESS_TERMCAP_me="$(tput sgr0)"
export LESS_TERMCAP_so="$(tput smso)"
export LESS_TERMCAP_se="$(tput rmso)"
export LESS_TERMCAP_us="$(tput smul)"
export LESS_TERMCAP_ue="$(tput rmul)"

# urlscanio
[[ -n "${URLSCAN_DATA_DIR}" ]] && mkdir --parents "${URLSCAN_DATA_DIR}"

# Includes
source "${XDG_CONFIG_HOME}/bash/aliases"
source "${XDG_CONFIG_HOME}/bash/functions"
source "${XDG_CONFIG_HOME}/bash/ssh_agent.sh"
source "${XDG_CONFIG_HOME}/bash/wsl.sh"

# rustup
source "${HOME}/.cargo/env"

# Starship Prompt
eval "$(starship init bash)"
